name: fb-dp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy>=1.15
  - pytorch>=1.3
  - torchvision>=0.4
  - tqdm>=4.40
  - scipy>=1.2
  - pytest
  - tensorboard=1.14.0
  - tensorflow
  - tensorboardX
  - pip
  - pip:
    - pytorch-dp
